export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  GET_ADDRESS_REQUEST: 'GET_ADDRESS_REQUEST',
  GET_ADDRESS_FAILURE: 'GET_ADDRESS_FAILURE',
  GET_ADDRESS_SUCCESS: 'GET_ADDRESS_SUCCESS',
  VERIFY_PHONE_REQUEST: 'VERIFY_PHONE_REQUEST',
  VERIFY_PHONE_FAILURE: 'VERIFY_PHONE_FAILURE',
  VERIFY_PHONE_SUCCESS: 'VERIFY_PHONE_SUCCESS',
  VERIFY_OTP_REQUEST: 'VERIFY_OTP_REQUEST',
  VERIFY_OTP_FAILURE: 'VERIFY_OTP_FAILURE',
  VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
  VERIFY_EMAIL_REQUEST: 'VERIFY_EMAIL_REQUEST',
  VERIFY_EMAIL_FAILURE: 'VERIFY_EMAIL_FAILURE',
  VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
  GET_BALANCE_REQUEST: 'GET_BALANCE_REQUEST',
  GET_BALANCE_FAILURE: 'GET_BALANCE_FAILURE',
  GET_BALANCE_SUCCESS: 'GET_BALANCE_SUCCESS',
  GET_EXCHANGE_REQUEST: 'GET_EXCHANGE_REQUEST',
  GET_EXCHANGE_FAILURE: 'GET_EXCHANGE_FAILURE',
  GET_EXCHANGE_SUCCESS: 'GET_EXCHANGE_SUCCESS',
};

export const userConstants = {
  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',
};


export const productsConstants = {
  PRODUCTS_REQUEST: 'PRODUCTS_REQUEST',
  PRODUCTS_SUCCESS: 'PRODUCTS_SUCCESS',
  PRODUCTS_FAILURE: 'PRODUCTS_FAILURE',
  PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
  PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',
  PRODUCT_DETAIL_FAILURE: 'PRODUCT_DETAIL_FAILURE',
  PRODUCT_ALLOCATIONS_REQUEST: 'PRODUCT_ALLOCATIONS_REQUEST',
  PRODUCT_ALLOCATIONS_SUCCESS: 'PRODUCT_ALLOCATIONS_SUCCESS',
  PRODUCT_ALLOCATIONS_FAILURE: 'PRODUCT_ALLOCATIONS_FAILURE',
  PRODUCT_ALLOCATION_DETAILS_REQUEST: 'PRODUCT_ALLOCATION_DETAILS_REQUEST',
  PRODUCT_ALLOCATION_DETAILS_SUCCESS: 'PRODUCT_ALLOCATION_DETAILS_SUCCESS',
  PRODUCT_ALLOCATION_DETAILS_FAILURE: 'PRODUCT_ALLOCATION_DETAILS_FAILURE',
};

export const transactionsConstants = {
  TRANSACTIONS_REQUEST: 'TRANSACTIONS_REQUEST',
  TRANSACTIONS_SUCCESS: 'TRANSACTIONS_SUCCESS',
  TRANSACTIONS_FAILURE: 'TRANSACTIONS_FAILURE',
  TRANSACTION_DETAIL_REQUEST: 'TRANSACTION_DETAIL_REQUEST',
  TRANSACTION_DETAIL_SUCCESS: 'TRANSACTION_DETAIL_SUCCESS',
  TRANSACTION_DETAIL_FAILURE: 'TRANSACTION_DETAIL_FAILURE',
};